spring.application.name=config-server


server.servlet.context-path=/config

server.port=9999

#localhost:9999/configserve   -> default path to access

spring.cloud.config.server.git.uri=https://github.com/WhooShubh/cloud-config.git