spring.application.name=recharge-service


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

server.port=8088

#this tells 100% of requests will be traced
management.tracing.sampling.probability=1.0
#this tells Send tracing data to the Zipkin server.
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans